version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/weaviate_database
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weaviate_database
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: